{{- with .Values.roles }}
{{- range . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name | required "Each role in .Values.roles must have a 'name' field." }}
  namespace: {{ default "default" .namespace }}
  labels:
    {{- include "role-call.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}
{{- end }}
