{{- with .Values.serviceAccounts }}
{{- range . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | required "Each service account in .Values.serviceAccounts must have a 'name' field." }}
  namespace: {{ default "default" .namespace }}
  labels:
    {{- include "role-call.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
